apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice:v0.10.6
          ports:
            - name: grpc
              containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 9555
          livenessProbe:
            grpc:
              port: 9555
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555